language: python

cache:
  - apt
  - pip

before_install:
  - sudo add-apt-repository -y ppa:anton+/dnscrypt
  - sudo apt-get update
  - |
    # install libzmq, libsodium unless zmq=bundled
    if [[ $ZMQ != bundled ]]; then
      sudo apt-get install -y -qq libzmq3-dev libsodium-dev
    fi
  - |
    # install cython unless pypy
    if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then
      pip install cython
    fi
  - |
    # build libzmq
    if [[ ! -z "$ZMQ" && $ZMQ != bundled ]]; then
      wget https://github.com/zeromq/$ZMQ/archive/master.zip -O libzmq.zip
      unzip libzmq.zip
      pushd "$ZMQ-master"
      ./autogen.sh
      ./configure --enable-drafts
      make -j
      sudo make install
      sudo ldconfig
      popd
      export ZMQ=/usr/local
      export ZMQ_DRAFT_API=1
    fi
  - pip install -r test-requirements.txt
  - pip install invoke cython requests
  - |
    # install pinned tornado
    if [[ "$TORNADO" == "master" ]]; then
      pip install https://github.com/tornadoweb/tornado/archive/master.zip
    elif [[ "$TORNADO" == "none" ]]; then
      pip uninstall -yq tornado
    elif [[ ! -z "$TORNADO" ]]; then
      pip install tornado==${TORNADO}
    fi
  - pip freeze

install:
  - python setup.py build_ext --inplace --zmq=$ZMQ
  - sudo apt-get install -y gcc
  - which python

matrix:
  include:
    - python: 3.7
      env: ZMQ=
      arch: arm64
      script: 
        - cd tools && invoke release 19.0.1
    - python: 3.7
      env: ZMQ=bundled
      arch: arm64
      script: 
        - cd tools && invoke release 19.0.1
  
deploy:
  provider: releases
  user: sakshi87
  password: allsoft12*
  file:
  - /io/wheelhouse/*.whl
  - /io/wheelhouse/*.tar.gz
  on:
    tags: false
    repo: sakshi87/pyzmq
  skip_cleanup: 'true'
